### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by darkness1998-black** [st4inl3s5/kizagan#3]
"Traceback (most recent call last):
  File "client.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "cv2\__init__.py", line 5, in <module>
ImportError: numpy.core.multiarray failed to import"
I got this error when building your python command, please help me:

**Comment by st4inl3s5** [comment]
you should update or redownload numpy library with following command :


python3 -m pip install numpy -I
